version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
  livello-product:
    image: anisbg/async-communication:livelloChallenge
    depends_on:
      - mosquitto