version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - /home/anis/Desktop/mosquitto-test/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
  livello-product:
    image: livello-challenge
    depends_on:
      - mosquitto